---

- name: define conditional variables
  set_fact:
    ipv4_forwarded: false

- name: check if ipv4 is forwarded
  command: sysctl net.ipv4.ip_forward
  register: ipv4_forward_output

- name: set ipv4_forwarded to true if ipv4 is forwarded
  set_fact:
    ipv4_forwarded: true
  # not(not found)
  when: ipv4_forward_output.stdout.find('net.ipv4.ip_forward = 1') != -1

- name: enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: true
  when: not ipv4_forwarded

- name: persist IPv4 forwarding on reboots
  command: sed -i 's/#net.ipv4.ip_forward/net.ipv4.ip_forward/g' /etc/sysctl.conf
  when: not ipv4_forwarded

- name: Retrieve private IP of the corresponding private node vm
  set_fact:
    node_private_ip_eth1: "{{ node_private_ip_map[inventory_hostname] }}"

- name: check if node_private_ip_eth1 is added to the NAT gateway
  command: iptables -t nat -L POSTROUTING -v
  register: nat_gateway_output

- name: Check if nf_conntrack module is already loaded
  command: lsmod | grep nf_conntrack
  register: nf_conntrack_check
  failed_when: false
  changed_when: false

- name: Debug - Show nf_conntrack module status
  debug:
    msg: "nf_conntrack module check result: rc={{ nf_conntrack_check.rc }}, stdout={{ nf_conntrack_check.stdout }}"

- name: Load nf_conntrack module if not already present
  modprobe:
    name: nf_conntrack
    state: present
  register: modprobe_result
  when: nf_conntrack_check.rc != 0

- name: Debug - Show modprobe result
  debug:
    msg: "modprobe result: {{ modprobe_result }}"
  when: nf_conntrack_check.rc != 0

# Nat randomized setup
- name: Add eth1 of node VM to the NAT gateway
  command: >
    iptables -t nat -A POSTROUTING -s {{ node_private_ip_eth1 }} -o eth0 -j MASQUERADE  --random
  when: nat_gateway_output.stdout.find(node_private_ip_eth1) == -1

- name: set netfilter conntrack max
  sysctl:
    name: net.netfilter.nf_conntrack_max
    value: 1048576
    state: present
    reload: true

- name: ensure netfilter conntrack max is set in sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    line: 'net.netfilter.nf_conntrack_max=1048576'
    state: present
