---
- name: get the latest version or a custom build of the RPC client
  ansible.builtin.get_url:
    url: "{{ safenode_rpc_client_archive_url }}"
    dest: /tmp/{{ safenode_rpc_client_archive_filename }}

- name: extract the RPC client binary to /usr/local/bin
  become: True
  ansible.builtin.unarchive:
    src: "/tmp/{{ safenode_rpc_client_archive_filename }}"
    dest: "{{ safenode_rpc_client_archive_dest_path }}"
    remote_src: True
