---
- name: start and enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: find the version0 json file
  find:
    paths: "{{ bootstrap_cache_dir }}"
    patterns: "*.json"
    recurse: no
  register: version0_file

- name: find the version1 json file
  find:
    paths: "{{ bootstrap_cache_dir }}/version_1"
    patterns: "*.json"
    recurse: no
  register: version1_file

- name: create a map of versions to their respective json files
  set_fact:
    version_files:
      version0: "{{ version0_file.files[0].path }}"
      version1: "{{ version1_file.files[0].path }}"

- name: ensure nginx is serving the json file using a template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: ensure nginx status site file is set
  template:
    src: nginx_status.conf.j2
    dest: /etc/nginx/sites-available/nginx_status

- name: ensure nginx status file symlink is present
  file:
    src: /etc/nginx/sites-available/nginx_status
    dest: /etc/nginx/sites-enabled/nginx_status
    state: link

- name: reload nginx to apply changes
  service:
    name: nginx
    state: reloaded
