---
# This role should be called before setting up the nodes
- name: define conditional variables
  set_fact:
    nat_gateway_is_configured: false

- debug: var=nat_gateway_private_ip_eth1

- name: execute ip route show command
  command: ip route show
  register: ip_route_output

- name: set nat_gateway_is_configured to true if nat gateway is configured
  set_fact:
    nat_gateway_is_configured: true
  when: ip_route_output.stdout.find(nat_gateway_private_ip_eth1) != -1

- name: Check if a backup netplan conf file exists
  stat:
    path: /etc/netplan/50-cloud-init.yaml.backup
  register: netplan_conf_backup

- name: obtain DO gateway ip
  command: curl -s http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/gateway
  register: do_gateway_ip
  when: not nat_gateway_is_configured and not netplan_conf_backup.stat.exists

- name: backup and configure the new netplan configuration file
  shell: |
    cp /etc/netplan/50-cloud-init.yaml /etc/netplan/50-cloud-init.yaml.backup
    sed -i '/eth0:/,/set-name: eth0/{/routes:/,/set-name: eth0/d}' /etc/netplan/50-cloud-init.yaml
    sed -i '/set-name: eth1/a\ \ \ \ \ \ \ \ \ \ \ \ routes:\n\ \ \ \ \ \ \ \ \ \ \ \ - \ \ to: 0.0.0.0/0\n\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ via: {{ nat_gateway_private_ip_eth1 }}' /etc/netplan/50-cloud-init.yaml
    sed -i '/eth0:/a\ \ \ \ \ \ \ \ \ \ \ \ routes:\n\ \ \ \ \ \ \ \ \ \ \ \ - \ \ \ to: 169.254.169.254\n\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ via: {{ do_gateway_ip.stdout }}\n\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ on-link: true' /etc/netplan/50-cloud-init.yaml
    sed -i '/^[ \t]*- [0-9.]*\/20[ \t]*$/d' /etc/netplan/50-cloud-init.yaml
  when: not nat_gateway_is_configured and not netplan_conf_backup.stat.exists

- name: apply the netplan rules
  command: netplan apply -debug
  when: not nat_gateway_is_configured