---
- name: check if antctl binary exists
  ansible.builtin.stat:
    path: "{{ binary_dir}}/antctl"
  register: antctl_binary

- name: download the antctl binary
  ansible.builtin.get_url:
    url: "{{ antctl_archive_url }}"
    dest: /tmp/{{ antctl_archive_filename }}
  when: not antctl_binary.stat.exists

- name: extract the antctl binary to /usr/local/bin
  become: True
  ansible.builtin.unarchive:
    src: "/tmp/{{ antctl_archive_filename }}"
    dest: "{{ binary_dir }}"
    remote_src: True
  when: not antctl_binary.stat.exists
