#!/usr/bin/env bash
set -e

terraform workspace delete -force angus-6
terraform workspace delete -force angus-build
terraform workspace delete -force angus-do
terraform workspace delete -force angus-f21
terraform workspace delete -force angus-l16
terraform workspace delete -force angus-latest
terraform workspace delete -force angus-latest2
terraform workspace delete -force angus-latest3
terraform workspace delete -force angus-mon11
terraform workspace delete -force angus-mon14
terraform workspace delete -force angus-mon18
terraform workspace delete -force angus-mon23
terraform workspace delete -force angus-mon25
terraform workspace delete -force angus-mon3
terraform workspace delete -force angus-mon32
terraform workspace delete -force angus-mon8
terraform workspace delete -force angus-mon9
terraform workspace delete -force angus-o
terraform workspace delete -force angus-t3
terraform workspace delete -force angus-w4
terraform workspace delete -force angus-w5
terraform workspace delete -force angus-w6
terraform workspace delete -force angus-w7
terraform workspace delete -force angus-w8
terraform workspace delete -force angus-wf11
terraform workspace delete -force angus-wf7
terraform workspace delete -force angus-wl1
terraform workspace delete -force angus-wll5
terraform workspace delete -force angus11
terraform workspace delete -force angus13
terraform workspace delete -force angus5
terraform workspace delete -force angus6
terraform workspace delete -force angus9
terraform workspace delete -force angusdocean
terraform workspace delete -force angusdos
terraform workspace delete -force angusnew
terraform workspace delete -force angusone
terraform workspace delete -force angustres
terraform workspace delete -force angusw
terraform workspace delete -force angusw1
terraform workspace delete -force angusww
terraform workspace delete -force anguswww
terraform workspace delete -force dev
terraform workspace delete -force main-now-withlibp2p-check
