---
- name: build binaries
  hosts: all
  become: False
  vars:
    build_ant_var: "{{ build_ant | default(true) }}"
    build_antnode_var: "{{ build_antnode | default(true) }}"
    build_antctl_var: "{{ build_antctl | default(true) }}"
    build_antctld_var: "{{ build_antctld | default(true) }}"
  roles:
    - {
        role: build_safe_network_binary,
        bin_name: "ant",
        when: (custom_bin == "true") and (build_ant_var | bool)
      }
    - {
        role: build_safe_network_binary,
        bin_name: "antnode",
        when: (custom_bin == "true") and (build_antnode_var | bool)
      }
    - {
        role: build_safe_network_binary,
        bin_name: "antctl",
        when: (custom_bin == "true") and (build_antctl_var | bool)
      }
    - {
        role: build_safe_network_binary,
        bin_name: "antctld",
        when: (custom_bin == "true") and (build_antctld_var | bool)
      }
