---
- name: upgrade the client telegraf configuration
  hosts: all
  roles:
    - role: telegraf-client
      become: True
  tasks:
    - name: restart telegraf service
      ansible.builtin.systemd:
        name: telegraf
        enabled: yes
        state: restarted
      register: telegraf_restart
      retries: 3
      delay: 5
      until: telegraf_restart is success
