---
- name: upgrade the node telegraf configuration
  hosts: all
  roles:
    - role: telegraf-node
      become: True
  tasks:
    - name: restart telegraf service
      ansible.builtin.systemd:
        name: telegraf
        enabled: yes
        state: restarted
      register: telegraf_restart
      retries: 3
      delay: 5
      until: telegraf_restart is success
    - name: restart telegraf-elasticsearch service
      ansible.builtin.systemd:
        name: telegraf-elasticsearch
        enabled: yes
        state: restarted
      register: telegraf_elasticsearch_restart
      retries: 3
      delay: 5
      until: telegraf_elasticsearch_restart is success
