---
org: maidsafe
branch: main
safenode_rpc_client_archive_filename: safenode_rpc_client-x86_64-unknown-linux-musl.tar.gz
safenode_rpc_client_archive_url: https://sn-node.s3.eu-west-2.amazonaws.com/{{ safenode_rpc_client_archive_filename }}
safenode_rpc_client_archive_dest_path: /usr/local/bin
